export default {
    styles: [
        "assets/css/bootstrap.min.css",
        "assets/css/owl.carousel.min.css",
        "assets/css/flaticon.css",
        "assets/css/slicknav.css",
        "assets/css/animate.min.css",
        "assets/css/magnific-popup.css",
        "assets/css/fontawesome-all.min.css",
        "assets/css/themify-icons.css",
        "assets/css/slick.css",
        "assets/css/nice-select.css",
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css",
        "assets/css/custom.css",
      ],
      scripts: [
        "js/vendor/modernizr-3.5.0.min.js",
        "js/vendor/jquery-1.12.4.min.js",
        "js/popper.min.js",
        "js/bootstrap.min.js",
        "js/owl.carousel.min.js",
        "js/slick.min.js",
        "js/wow.min.js",
        "js/animated.headline.js",
        "js/jquery.magnific-popup.js",
        "js/jquery.scrollUp.min.js",
        "js/jquery.nice-select.min.js",
        "js/jquery.sticky.js",
        "js/jquery.form.js",
        "js/jquery.validate.min.js",
        "js/mail-script.js",
        "js/jquery.ajaxchimp.min.js",
        "js/contact.js",
        "js/plugins.js",
        "js/main.js",
      ],
}